---
- hosts: all
  become: true
  roles:
    - role: nginxinc.nginx
      vars:
        ansible_python_interpreter: /bin/python
  post_tasks:
    - name: Upload website files
      copy: src=../files/website/ dest=/usr/share/nginx/html/ mode=0644

